spring:
  application:
    name: gateway-server

  profiles:
    active: local

  http:
    codecs:
      # 调整缓冲区大小，保持与 Java 版一致
      max-in-memory-size: 10MB

  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true
      fail-on-empty-beans: false

  main:
    allow-circular-references: true

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: system-admin-api
              uri: grayLb://system-server
              predicates:
                - Path=/admin-api/system/**
              filters:
                - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs
            - id: system-app-api
              uri: grayLb://system-server
              predicates:
                - Path=/app-api/system/**
              filters:
                - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs
            - id: infra-admin-api
              uri: grayLb://infra-server
              predicates:
                - Path=/admin-api/infra/**
              filters:
                - RewritePath=/admin-api/infra/v3/api-docs, /v3/api-docs
            - id: infra-app-api
              uri: grayLb://infra-server
              predicates:
                - Path=/app-api/infra/**
              filters:
                - RewritePath=/app-api/infra/v3/api-docs, /v3/api-docs
            - id: infra-spring-boot-admin
              uri: grayLb://infra-server
              predicates:
                - Path=/admin/**
            - id: infra-websocket
              uri: grayLb://infra-server
              predicates:
                - Path=/infra/ws/**
            - id: member-admin-api
              uri: grayLb://member-server
              predicates:
                - Path=/admin-api/member/**
              filters:
                - RewritePath=/admin-api/member/v3/api-docs, /v3/api-docs
            - id: member-app-api
              uri: grayLb://member-server
              predicates:
                - Path=/app-api/member/**
              filters:
                - RewritePath=/app-api/member/v3/api-docs, /v3/api-docs
            - id: bpm-admin-api
              uri: grayLb://bpm-server
              predicates:
                - Path=/admin-api/bpm/**
              filters:
                - RewritePath=/admin-api/bpm/v3/api-docs, /v3/api-docs
            - id: report-admin-api
              uri: grayLb://report-server
              predicates:
                - Path=/admin-api/report/**
              filters:
                - RewritePath=/admin-api/report/v3/api-docs, /v3/api-docs
            - id: report-jimu
              uri: grayLb://report-server
              predicates:
                - Path=/jmreport/**, /drag/**, /jimubi/**
            - id: pay-admin-api
              uri: grayLb://pay-server
              predicates:
                - Path=/admin-api/pay/**
              filters:
                - RewritePath=/admin-api/pay/v3/api-docs, /v3/api-docs
            - id: pay-app-api
              uri: grayLb://pay-server
              predicates:
                - Path=/app-api/pay/**
              filters:
                - RewritePath=/app-api/pay/v3/api-docs, /v3/api-docs
            - id: mp-admin-api
              uri: grayLb://mp-server
              predicates:
                - Path=/admin-api/mp/**
              filters:
                - RewritePath=/admin-api/mp/v3/api-docs, /v3/api-docs
            - id: product-admin-api
              uri: grayLb://product-server
              predicates:
                - Path=/admin-api/product/**
              filters:
                - RewritePath=/admin-api/product/v3/api-docs, /v3/api-docs
            - id: product-app-api
              uri: grayLb://product-server
              predicates:
                - Path=/app-api/product/**
              filters:
                - RewritePath=/app-api/product/v3/api-docs, /v3/api-docs
            - id: promotion-admin-api
              uri: grayLb://promotion-server
              predicates:
                - Path=/admin-api/promotion/**
              filters:
                - RewritePath=/admin-api/promotion/v3/api-docs, /v3/api-docs
            - id: promotion-app-api
              uri: grayLb://promotion-server
              predicates:
                - Path=/app-api/promotion/**
              filters:
                - RewritePath=/app-api/promotion/v3/api-docs, /v3/api-docs
            - id: trade-admin-api
              uri: grayLb://trade-server
              predicates:
                - Path=/admin-api/trade/**
              filters:
                - RewritePath=/admin-api/trade/v3/api-docs, /v3/api-docs
            - id: trade-app-api
              uri: grayLb://trade-server
              predicates:
                - Path=/app-api/trade/**
              filters:
                - RewritePath=/app-api/trade/v3/api-docs, /v3/api-docs
            - id: statistics-admin-api
              uri: grayLb://statistics-server
              predicates:
                - Path=/admin-api/statistics/**
              filters:
                - RewritePath=/admin-api/statistics/v3/api-docs, /v3/api-docs
            - id: erp-admin-api
              uri: grayLb://erp-server
              predicates:
                - Path=/admin-api/erp/**
              filters:
                - RewritePath=/admin-api/erp/v3/api-docs, /v3/api-docs
            - id: crm-admin-api
              uri: grayLb://crm-server
              predicates:
                - Path=/admin-api/crm/**
              filters:
                - RewritePath=/admin-api/crm/v3/api-docs, /v3/api-docs
            - id: ai-admin-api
              uri: grayLb://ai-server
              predicates:
                - Path=/admin-api/ai/**
              filters:
                - RewritePath=/admin-api/ai/v3/api-docs, /v3/api-docs
            - id: ai-mcp-server
              uri: grayLb://ai-server
              predicates:
                - Path=/sse, /mcp/message
            - id: iot-admin-api
              uri: grayLb://iot-server
              predicates:
                - Path=/admin-api/iot/**
              filters:
                - RewritePath=/admin-api/iot/v3/api-docs, /v3/api-docs
          x-forwarded:
            prefix-enabled: false

server:
  port: 48080

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

knife4j:
  gateway:
    enabled: true
    routes:
      - name: system-server
        service-name: system-server
        url: /admin-api/system/v3/api-docs
      - name: infra-server
        service-name: infra-server
        url: /admin-api/infra/v3/api-docs
      - name: member-server
        service-name: member-server
        url: /admin-api/member/v3/api-docs
      - name: bpm-server
        service-name: bpm-server
        url: /admin-api/bpm/v3/api-docs
      - name: pay-server
        service-name: pay-server
        url: /admin-api/pay/v3/api-docs
      - name: mp-server
        service-name: mp-server
        url: /admin-api/mp/v3/api-docs
      - name: product-server
        service-name: product-server
        url: /admin-api/product/v3/api-docs
      - name: promotion-server
        service-name: promotion-server
        url: /admin-api/promotion/v3/api-docs
      - name: trade-server
        service-name: trade-server
        url: /admin-api/trade/v3/api-docs
      - name: statistics-server
        service-name: statistics-server
        url: /admin-api/statistics/v3/api-docs
      - name: erp-server
        service-name: erp-server
        url: /admin-api/erp/v3/api-docs
      - name: crm-server
        service-name: crm-server
        url: /admin-api/crm/v3/api-docs
      - name: ai-server
        service-name: ai-server
        url: /admin-api/ai/v3/api-docs
      - name: iot-server
        service-name: iot-server
        url: /admin-api/iot/v3/api-docs

daoyi:
  info:
    version: 1.0.0
