[package]
name = "daoyi-module-system"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
daoyi-framework = { path = "../daoyi-framework" }
salvo.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
