[package]
name = "daoyi-server"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "daoyi-server"
path = "src/main.rs"

[dependencies]
daoyi-framework = { path = "../daoyi-framework" }
daoyi-gateway = { path = "../daoyi-gateway" }
salvo.workspace = true
tracing.workspace = true
